name: Daily Python Script Run

on:
  schedule:
    # Runs at 16:00 (4:00 PM) UK time (which is UTC+0 in winter, UTC+1 in summer)
    # So we use UTC time here:
    # During British Summer Time (BST), 4 PM UK = 15:00 UTC
    # During GMT, 4 PM UK = 16:00 UTC
    - cron: "0 15 * 4-10 *"   # BST months (Apr–Oct)
    - cron: "0 16 * 11-3 *"   # GMT months (Nov–Mar)
  workflow_dispatch:  # allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: |
        python main.py
