name:  MACD SMA Screener

on:
  schedule:
    - cron: "0 15 * * *"  # 16:00 UTC → adjust for DST if necessary
    workflow_dispatch:  # Manual trigger for testing

jobs:
  test_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas numpy
          
      - name: Run Python Script
        run: python macd_negative_crossover_email_csv_env.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
